name: Javadoc and GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Updated to match your pom.xml
          distribution: 'temurin'  # Corrected distribution

      - name: Build project and generate Javadoc
        run: mvn clean install javadoc:javadoc

      - name: Clone project
        uses: actions/checkout@v4
        with:
          ref: doc

      - name: Deploy Javadoc to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "rania.chouchene.2019@gmail.com"
          git config --global user.name "Rania Chouchene"
          mkdir -p docs
          cp -r target/site/apidocs/* docs/
          cd docs
          git add .
          git commit -m "Update Javadoc" || echo "ignore commit failure, proceed"
          git push origin docs
     
